package com.aurora.modifypositioning.model

import com.aurora.modifypositioning.location.InjectorState

data class DiagnosticLocation(
    val provider: String,
    val latitude: Double,
    val longitude: Double,
    val accuracyMeters: Float,
    val timeMillis: Long,
    val isMock: Boolean,
    val distanceToLastInjectionMeters: Double? = null,
)

data class DiagnosticInjectorStatus(
    val id: String,
    val displayName: String,
    val state: InjectorState,
    val lastSuccessAtMillis: Long?,
    val lastFailureAtMillis: Long?,
    val lastErrorCode: String?,
)

data class DiagnosticSnapshot(
    val generatedAtMillis: Long,
    val deviceManufacturer: String,
    val deviceModel: String,
    val androidVersion: String,
    val androidApiLevel: Int,
    val appVersionName: String,
    val appVersionCode: Long,
    val isMockAppSelected: Boolean,
    val missingPermissions: List<String>,
    val gpsEnabled: Boolean,
    val networkEnabled: Boolean,
    val gpsLastKnown: DiagnosticLocation?,
    val networkLastKnown: DiagnosticLocation?,
    val fusedAvailable: Boolean,
    val fusedMockModeEnabled: Boolean,
    val fusedMockModePending: Boolean,
    val fusedLastInjectionPending: Boolean,
    val fusedLastInjectionTimeMillis: Long?,
    val fusedLastSuccessfulLatitude: Double?,
    val fusedLastSuccessfulLongitude: Double?,
    val fusedLastError: String?,
    val injectorOverallState: InjectorState,
    val injectorActiveCount: Int,
    val injectorFailedCount: Int,
    val injectorStatuses: List<DiagnosticInjectorStatus>,
    val injectorWarning: String?,
    val appState: MockState,
    val lastInjection: InjectionReport?,
    val movementMode: MovementMode,
    val movementState: MovementState,
    val movementCurrentSpeedMps: Double,
    val movementDistanceFromCenterMeters: Double,
    val movementLastPointTimeMillis: Long?,
    val routeMode: MovementMode?,
    val travelMode: TravelMode?,
    val routeSource: RouteSource?,
    val remainingDistanceMeters: Double?,
    val remainingDurationSeconds: Double?,
    val routeProgressPercent: Double?,
    val calibrationMode: CoordinateCalibrationMode,
    val searchRequestCount: Int,
)
